apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventcom-goapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eventcom-goapp
  template:
    metadata:
      labels:
        app: eventcom-goapp
    spec:
      containers:
      - name: eventcom-goapp
        image: gcr.io/tidy-arena-419316/eventcom-goapp:v2
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: uri
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
