// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: rpc_create_post.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email        string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Name         string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Role         string   `protobuf:"bytes,3,opt,name=Role,proto3" json:"Role,omitempty"`
	Organisation string   `protobuf:"bytes,4,opt,name=Organisation,proto3" json:"Organisation,omitempty"`
	Contact      string   `protobuf:"bytes,5,opt,name=Contact,proto3" json:"Contact,omitempty"`
	KindofTalk   []string `protobuf:"bytes,6,rep,name=KindofTalk,proto3" json:"KindofTalk,omitempty"`
	Title        string   `protobuf:"bytes,7,opt,name=Title,proto3" json:"Title,omitempty"`
	Description  string   `protobuf:"bytes,8,opt,name=Description,proto3" json:"Description,omitempty"`
	Dates        []string `protobuf:"bytes,9,rep,name=Dates,proto3" json:"Dates,omitempty"`
	ExtraDetails string   `protobuf:"bytes,10,opt,name=ExtraDetails,proto3" json:"ExtraDetails,omitempty"`
	Location     string   `protobuf:"bytes,11,opt,name=Location,proto3" json:"Location,omitempty"`
	Status       string   `protobuf:"bytes,12,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_create_post_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_post_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_post_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePostRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreatePostRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePostRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreatePostRequest) GetOrganisation() string {
	if x != nil {
		return x.Organisation
	}
	return ""
}

func (x *CreatePostRequest) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *CreatePostRequest) GetKindofTalk() []string {
	if x != nil {
		return x.KindofTalk
	}
	return nil
}

func (x *CreatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePostRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePostRequest) GetDates() []string {
	if x != nil {
		return x.Dates
	}
	return nil
}

func (x *CreatePostRequest) GetExtraDetails() string {
	if x != nil {
		return x.ExtraDetails
	}
	return ""
}

func (x *CreatePostRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreatePostRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_rpc_create_post_proto protoreflect.FileDescriptor

var file_rpc_create_post_proto_rawDesc = []byte{
	0x0a, 0x15, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x6f, 0x73,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xd5, 0x02, 0x0a, 0x11,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x52,
	0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x73, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x4b, 0x69, 0x6e, 0x64, 0x6f, 0x66, 0x54, 0x61, 0x6c, 0x6b, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0a, 0x4b, 0x69, 0x6e, 0x64, 0x6f, 0x66, 0x54, 0x61, 0x6c, 0x6b, 0x12, 0x14, 0x0a,
	0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x44, 0x61, 0x74, 0x65, 0x73, 0x18, 0x09,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x44, 0x61, 0x74, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x45,
	0x78, 0x74, 0x72, 0x61, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x45, 0x78, 0x74, 0x72, 0x61, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x77, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x76, 0x6f, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e,
	0x67, 0x2d, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x64, 0x62, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_create_post_proto_rawDescOnce sync.Once
	file_rpc_create_post_proto_rawDescData = file_rpc_create_post_proto_rawDesc
)

func file_rpc_create_post_proto_rawDescGZIP() []byte {
	file_rpc_create_post_proto_rawDescOnce.Do(func() {
		file_rpc_create_post_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_create_post_proto_rawDescData)
	})
	return file_rpc_create_post_proto_rawDescData
}

var file_rpc_create_post_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rpc_create_post_proto_goTypes = []interface{}{
	(*CreatePostRequest)(nil), // 0: pb.CreatePostRequest
}
var file_rpc_create_post_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_create_post_proto_init() }
func file_rpc_create_post_proto_init() {
	if File_rpc_create_post_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_create_post_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_create_post_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_post_proto_goTypes,
		DependencyIndexes: file_rpc_create_post_proto_depIdxs,
		MessageInfos:      file_rpc_create_post_proto_msgTypes,
	}.Build()
	File_rpc_create_post_proto = out.File
	file_rpc_create_post_proto_rawDesc = nil
	file_rpc_create_post_proto_goTypes = nil
	file_rpc_create_post_proto_depIdxs = nil
}
